name: CI/CD Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/tha_drop_backend
            git reset --hard origin/master
            git pull origin master
            docker stop tha-bank-backend 
            docker rm tha-bank-backend 
            docker buildx build --platform linux/amd64 -t tha-bank-backend:latest --load .
            docker run -d -p 8080:8080 --env-file .env --restart on-failure --name tha-bank-backend tha-bank-backend:latest
